export const CONFIG = {
    BATCH_EMBED_SIZE: 5,
    CRAWL_CONCURRENCY: 3,
    DEFAULT_MAX_PAGES: 25,
    VECTOR_SCORE_THRESHOLD: 0.2,
    MAX_PROMPT_CHUNKS: 8,
    EMBEDDING_CACHE_TTL: 86400, // 24 hours
    DEBUG_LOGGING: true,

    // Advanced RAG constants
    SEMANTIC_CHUNK_MIN_SIZE: 200,
    SEMANTIC_CHUNK_MAX_SIZE: 1500,
    HYBRID_SEARCH_WEIGHT_SEMANTIC: 0.7,
    HYBRID_SEARCH_WEIGHT_LEXICAL: 0.3,
    LEXICAL_INDEX_MIN_TERM_LENGTH: 3
};
